import{a as b,i as n,S as w}from"./assets/vendor-D0cagnvz.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))f(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const p of r.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&f(p)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function f(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();async function y(o){return await b(o)}function m(o){return o.map(e=>` <li class="gallery-item">
      <a href="${e.largeImageURL}"><img class="img" src="${e.webformatURL}" alt="${e.tags}"/></a>
      <div class="card-wrapper"><p class="like text">Likes<span class="content">${e.likes}</span></p>
      <p class="view text">Views<span class="content">${e.views}</span></p>
      <p class="comment text">Comments<span class="content">${e.comments}</span></p>
      <p class="download text">Downloads<span class="content">${e.downloads}</span></p></div>
      
    </li>`).join("")}const g=document.querySelector(".form");document.querySelector(".btn");const l=document.querySelector(".gallery");document.querySelector(".text-input");const c=document.querySelector(".loader"),a=document.querySelector(".load-more"),d=15;let h="",i=1;g.addEventListener("submit",L);l.addEventListener("click",$);a.addEventListener("click",S);async function L(o){o.preventDefault();const e=o.target.elements.text.value.trim();if(h=e,i=1,e==="")return n.warning({title:"",position:"topRight",message:"You forgot to fill the field!"});g.reset(),l.innerHTML="",c.style.display="block",a.style.display="none";try{const s=await y(`https://pixabay.com/api/?key=47394436-b99c7e5d1cf7e77b7cf55ecb6&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${i}&per_page=${d}
`);if(s.data.total===0)return n.error({title:"",position:"topRight",message:'"Sorry, there are no images matching your search query. Please try again!"'});u.refresh(),l.insertAdjacentHTML("beforeend",m(s.data.hits)),s.data.total>15&&(a.style.display="block")}catch{n.error({title:"",position:"topRight",message:"Oooops! Somthing went wrong :/"})}finally{c.style.display="none"}}async function S(){i++,c.style.display="block",a.disabled=!0;const o=document.querySelector(".gallery-item"),{height:e}=o.getBoundingClientRect();try{const s=await y(`https://pixabay.com/api/?key=47394436-b99c7e5d1cf7e77b7cf55ecb6&q=${h}&image_type=photo&orientation=horizontal&safesearch=true&page=${i}&per_page=${d}`);l.insertAdjacentHTML("beforeend",m(s.data.hits)),u.refresh(),window.scrollBy({top:e*2,left:0,behavior:"smooth"}),i>=s.data.totalHits/d&&(a.style.display="none",n.warning({title:"",position:"bottomCenter",message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({title:"",position:"topRight",message:"Oooops! Somthing went wrong :/"})}finally{c.style.display="none",a.disabled=!1}}let u=new w(".gallery-item a",{captions:!0,captionsData:"alt",captionDelay:250});function $(o){o.preventDefault(),o.target.nodeName==="IMG"&&u.on("show.simplelightbox")}
//# sourceMappingURL=index.js.map
